CREATE TABLE event_log (
	id int,
	id_mosquito int,
	dia int,
	hora int,
	temperatura float,
	sexo character varying(100),
	expectativa_de_vida float,
	tiempo_de_vida float,
	tiempo_madurez float,
	madurez float,
	tipo_zona character varying(100),
	esta_muerto boolean,
	ultima_oviposicion int,
	ultimo_alimento int,
	distancia_recorrida int,
	cantidad_oviposicion int,
	cantidad_alimentacion int,
	is_inseminada boolean,
	se_alimenta boolean,
	se_reproduce boolean,
	pone_huevos boolean,
	cantidad_huevos int,
	estado character varying(100),
	posicion_x float,
	posicion_y float ) 